### ISSUE TITLE
How to Detect and Fix Broken Links?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/nextra-demo#10]
Since moving to `Nextra` _many_ of the _internal_ links in our docs are broken  ... 💔 😢 
One thing that `Docusaurus` gave us out-of-the-box was checking links. 🦕 📜 
We need to investigate if `Nextra` has the feature to check all links in a page and confirm they work. 🔗 👍 

# Todo

+ [x] Investigate if `Nextra` has a built-in way to check _internal_ links to confirm they aren't `404`. 📥 
+ [x] Same for _external_ links but this probably won't be a thing as it requires making outbound HTTP requests. 🌐 

If there is an _easy_ way to check the _internal_ links please share and _implement_ on this `demo` with instructions. 📝 🙏 
Please add comments for your searches and pages you read along the way so others don't have to waste the same time. ⏳

**Comment by LuchoTurtle** [comment]
`Nextra` doesn't have much information about linting and validating internal links :( The only reference to internal links is in https://nextra.site/docs/guide/link, which just explains how they render the links in `mdx` files and convert it to `Next.js`'s `Link` components. There doesn't seem to be any issues or discussions regarding this in their repo either.

However, I've found a couple of packages that may tackle this issue:
- https://www.reddit.com/r/nextjs/comments/1aonrjs/you_dont_have_worry_about_broken_links_in_your/
- https://github.com/ckastbjerg/next-type-safe-routes

Let me give these a whirl.

**Comment by LuchoTurtle** [comment]
I've been trying a couple of options:

# https://github.com/ckastbjerg/next-type-safe-routes

Using https://github.com/ckastbjerg/next-type-safe-routes was my first attempt. However, this attempt was not successful. On my first attempt to get it to work, I was met with a lot of errors.

![image](https://github.com/user-attachments/assets/8458bff5-2473-4ac9-ba53-fc8f707d6fed)

However, even with these, the routes were not being properly validated. And there was no discernable way of actually *linting* the links at build time/running on dev mode. 

In addition to this, it seemed that `rewrites` was not properly supported (as discussed in https://github.com/ckastbjerg/next-type-safe-routes/issues/15), so we couldn't properly use this plugin.

# https://github.com/triyanox/next-routes

Came across this one on Reddit and seemed promising. However, having tried to incorporate this into our `Nextra` app, it seemed that this package is oriented to the routing made with the [`App Router`](https://nextjs.org/docs/app) and not with [`Pages Router`](https://nextjs.org/docs/pages). Additionally, it didn't support the file directory with `.mdx` files or [slugs](https://github.com/triyanox/next-routes#roadmap) (which it would have been a similar way of parsing the files).

So unfortunately, this was a dud :( 

# https://github.com/contentlayerdev/contentlayer

`contentlayer` is used to get the site's data. It supports [`Next.js` ](https://contentlayer.dev/docs/environments/nextjs-dcf8e39e), and by extension, `Nextra`.

I thought of using `contentlayer` with https://github.com/tcort/markdown-link-check to recursively go over through the site data (generated by `contentlayer` and check the URLs that are found within the `mdx` files. 

> [!NOTE]
>
> https://github.com/tcort/markdown-link-check/issues/216 states that `localhost` links may not work in later versions but I'm using the latest versions still because they are still found (using `3.12.2`).

So, I set out to integrate `contentlayer` in this demo, following https://www.imadatyat.me/guides/how-to-setup-contentlayer-in-nextjs#add-a-jsconfigjson-file. 

After setting all of the necessary imports, files and configuration to the demo, when trying to run `contentlayer build` in my `package.json` file, I was prompted with the following error:

```sh
Generated 11 documents in .contentlayer
TypeError: The "code" argument must be of type number. Received an instance of Object
    at process.set [as exitCode] (node:internal/bootstrap/node:123:9)
    at Cli.runExit (/Users/lucho/Documents/dwyl/nextra-demo/node_modules/.pnpm/clipanion@3.2.1_typanion@3.14.0/node_modules/clipanion/lib/advanced/Cli.js:232:26)
    at run (file:///Users/lucho/Documents/dwyl/nextra-demo/node_modules/.pnpm/@contentlayer+cli@0.3.4_esbuild@0.21.5/node_modules/@contentlayer/cli/src/index.ts:39:3)
    at main (/Users/lucho/Documents/dwyl/nextra-demo/node_modules/.pnpm/contentlayer@0.3.4_esbuild@0.21.5/node_modules/contentlayer/bin/cli.cjs:5:3) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

The files are *actually being generated*.

![image](https://github.com/user-attachments/assets/1da44224-cd96-4257-ba3d-84c971d46fb7)

But the error cumbersomely still pops up. So I found out about the issue https://github.com/contentlayerdev/contentlayer/issues/495, where the error seemed to be related with the `Node` version. Long story short, `Node 18` works but `Node 19` had deprecated a piece of code at https://nodejs.org/api/deprecations.html#DEP0164 that no longer exists in `Node 20`. **I'm not willing to downgrade to `Node 20` for this**. 

Looking over the issues in the repo, I came across https://github.com/contentlayerdev/contentlayer/issues/429#issuecomment-1974928678. Apparently, `Netlify` acquired the project and it was put on the back burner (why is `Netlify` slowly killing acquired FOSS projects? 🤔). So, following the recommendation of https://github.com/contentlayerdev/contentlayer/issues/651#issuecomment-2030335434, while they are coordinating the maintenance roadmap for the project, I'm going to have to use https://github.com/timlrx/contentlayer2, a fork of the original project that is actively being maintained (and hopefully, in the future, will have its changed merged back into the official upstream `contentlayer` package).

After migrating, I'm trying to run the `markdownLintCheck` from `markdown-lin-check` but I'm coming across an error similar to the one described in https://github.com/tcort/markdown-link-check/issues/272.

**Comment by LuchoTurtle** [comment]
Hmm, I almost got it working with the combination of `contentlayer2` and `markdown-link-check`. But now I've stumbled upon https://github.com/theoludwig/markdownlint-rule-relative-links and maybe I can use this too (or replace everything completely with this? It doesn't **check if the path exists**, just if the file does (which is ultimately the same thing? 🤔)

**Comment by nelsonic** [comment]
@LuchoTurtle thanks very much for taking a deep dive into this. 🙏  
My takeaway is: this is _not_ a built-in feature of `Nextra` ... 😕 
Feels like it _should_ be. 🤷‍♂️ 

Keen to see what you have to do to get this working. 👍 
But equally I'm leaning towards proposing using (building) something `else` that better suits our (client's) needs. 💭
